# MODEL EVALUATION AND REQUIREMENT

In [1]:
!pip install ipywidgets

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
path ='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/module_5_auto.csv'
df=pd.read_csv(path)

In [4]:
df.to_csv('module_5_auto.csv')

In [5]:
df=df._get_numeric_data()
df.head()

Unnamed: 0.1  Unnamed: 0  symboling  normalized-losses  wheel-base  \
0             0           0          3                122        88.6   
1             1           1          3                122        88.6   
2             2           2          1                122        94.5   
3             3           3          2                164        99.8   
4             4           4          2                164        99.4   

     length     width  height  curb-weight  engine-size  ...  stroke  \
0  0.811148  0.890278    48.8         2548          130  ...    2.68   
1  0.811148  0.890278    48.8         2548          130  ...    2.68   
2  0.822681  0.909722    52.4         2823          152  ...    3.47   
3  0.848630  0.919444    54.3         2337          109  ...    3.40   
4  0.848630  0.922222    54.3         2824          136  ...    3.40   

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0                9.0       111.0    5000.0        21           27  13495.0   
1                9.0       111.0    5000.0        21           27  16500.0   
2                9.0       154.0    5000.0        19           26  16500.0   
3               10.0       102.0    5500.0        24           30  13950.0   
4                8.0       115.0    5500.0        18           22  17450.0   

   city-L/100km  diesel  gas  
0     11.190476       0    1  
1     11.190476       0    1  
2     12.368421       0    1  
3      9.791667       0    1  
4     13.055556       0    1  

[5 rows x 21 columns]

In [6]:
from ipywidgets import interact,interactive,fixed,interact_manual

In [7]:
def Distribution(RedFunction,BlueFunction,RedName,BlueName,Title):
    width=12
    height=10
    plt.figure(figsize=(width,height))
    ax1=sns.distplot(RedFunction,hist=False,color="r",label=RedName)
    ax2=sns.distplot(BlueFunction,hist=False,color="b",label=BlueName,ax=ax1)

    plt.title(Title)
    plt.xlabel('Price(in dollars)')
    plt.ylabel('Proportion of Cars')

    plt.show()
    plt.close()

In [8]:
def PollyPlot(xtrain,xtest,y_train,y_test,lr,poly_transforma):
    width=12
    height=10
    plt.figure(figsize=(width,height))
    xmax=max([xtrain.values.max(),xtest.values.max()])
    xmin=min([xtrain.values.min(),xtest.values.min()])
    x=np.arange(xmin,xmax,0.1)
    
    plt.plot(xtrain,y_train,'ro',label='Training Data')
    plt.plot(xtest,y_test,'go',label='Test Data')
    plt.plot(x,lr.predict(poly_transform.fit_transform(x.reshape(-1,1),label='Predicted Function')))
    plt.ylim([-10000,60000])
    plt.ylabel('Price')
    plt.legend()

In [9]:
# Part 1 :Training and Testing

In [10]:
y_data=df['price']

In [11]:
x_data=df.drop('price',axis=1)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.10,random_state=1)
print(x_test.shape[0])
print(x_train.shape[0])


21
180


In [13]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x_data,y_data,test_size=0.4,random_state=0)
print("number of test samples:",x_test1.shape[0])
print("number of training samples:",x_train1.shape[0])

number of test samples: 81
number of training samples: 120


In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lm=LinearRegression()

In [16]:
lm.fit(x_train[['horsepower']],y_train)

LinearRegression()

In [17]:
lm.score(x_train[['horsepower']],y_train)

0.6619724197515103

In [18]:
lm.fit(x_test[['horsepower']],y_test)

LinearRegression()

In [19]:
lm.score(x_test[['horsepower']],y_test)


0.41827774184282707

In [20]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x_data,y_data,test_size=0.4,random_state=0)
lm.fit(x_train1[['horsepower']],y_train1)
lm.score(x_test1[['horsepower']],y_test1)

0.7139364665406973

### Cross-Validation Score

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
Rcross=cross_val_score(lm,x_data[['horsepower']],y_data,cv=4)

In [23]:
Rcross

array([0.7746232 , 0.51716687, 0.74785353, 0.04839605])

In [24]:
print("The mean of the folds are",Rcross.mean(),"and the standard deviation is",Rcross.std())

The mean of the folds are 0.522009915042119 and the standard deviation is 0.2911839444756029


In [25]:
-1*cross_val_score(lm,x_data[['horsepower']],y_data,cv=4,scoring='neg_mean_squared_error')

array([20254142.84026704, 43745493.2650517 , 12539630.34014931,
       17561927.72247591])

In [26]:
Rc=cross_val_score(lm,x_data[['horsepower']],y_data,cv=2)
Rc.mean()

0.5166761697127429

In [27]:
from sklearn.model_selection import cross_val_predict

In [28]:
yhat=cross_val_predict(lm,x_data[["horsepower"]],y_data,cv=4)
yhat[0:5]

array([14141.63807508, 14141.63807508, 20814.29423473, 12745.03562306,
       14762.35027598])

In [29]:
# Part 2: Overfitting ,Underfitting Model Selection

In [30]:
lr=LinearRegression()

In [31]:
lr.fit(x_train[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']], y_train)

LinearRegression()

In [32]:
yhat_train = lr.predict(x_train[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']])
yhat_train[0:5]

array([ 7426.6731551 , 28323.75090803, 14213.38819709,  4052.34146983,
       34500.19124244])

In [33]:
yhat_test = lr.predict(x_test[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']])
yhat_test[0:5]

array([11349.35089149,  5884.11059106, 11208.6928275 ,  6641.07786278,
       15565.79920282])

In [34]:
import matplotlib.pyplot as plt 
%matplotlib inline 
import seaborn as sns 

In [35]:
Title = 'Distribution  Plot of  Predicted Value Using Training Data vs Training Data Distribution'
DistributionPlot(y_train, yhat_train, "Actual Values (Train)", "Predicted Values (Train)", Title)

NameError: name 'DistributionPlot' is not defined

In [ ]:
Title='Distribution  Plot of  Predicted Value Using Test Data vs Data Distribution of Test Data'
DistributionPlot(y_test,yhat_test,"Actual Values (Test)","Predicted Values (Test)",Title)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.45, random_state=0)

In [ ]:
pr=PolynomialFeatures(degree=5)
x_train_pr=pr.fit_transform(x_train[['horsepower']])
x_test_pr=pr.fit_trandform(x_test[['horsepower']])
pr

In [ ]:
poly=LinearRegression()
poly.fit(x_train_pr,y_train)

In [ ]:
yhat=poly.predict(x_test_pr)
yhat[0:5]

In [ ]:
print(yhat[0:4])
print(y_test[0:4].values)

In [ ]:
PollyPlot(x_train[['horsepower']], x_test[['horsepower']], y_train, y_test, poly,pr)

In [ ]:
Poly.score(x_train_pr,y_train)
poly.score(x_test_pr,y_test)